version: '2'
services:
  db:
    container_name: hello.db
    image: postgres:9.6
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456    

  web:
    container_name: hello.web
    build: .
    restart: always
    ports:
      - "7000:5000"
    depends_on:
      - db
    links:
      - db    
      
  reverse-proxy:
    container_name: hello.proxy
    image: nginx
    depends_on:
      - web
    ports:
      - "9090:8080"
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf    
